apiVersion: v1
kind: Service
metadata:
  name: my-static-portfolio
  labels:
    app: my-static-portfolio
spec:
  selector:
    app: my-static-portfolio

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP
